const catalogData = {
  catalog: {
    version: '1.0.0',
    default_locale: 'en',
    currency_mode: 'market_based',
    supported_markets: [
      {
        code: 'LB',
        name: 'Lebanon',
        currency: 'USD',
      },
    ],
    products: [
      {
        id: 'food_basic_kit',
        sku: 'BUNDLE-FOOD-BASIC-001',
        slug: 'basic-food-assistance-kit',
        type: 'bundle',
        status: 'active',
        category: {
          id: 'food',
          name: 'Food',
        },
        tags: ['donation', 'food', 'aid', 'bundle', 'essential'],
        title: 'Basic Food Assistance Kit',
        subtitle: 'Essential pantry staples for daily nutrition',
        description:
          'A donation bundle containing essential food supplies designed to support individuals or families in need with basic pantry staples and ready-to-use items.',
        short_description: 'Essential food support bundle for daily nutrition.',
        brand: null,
        vendor: null,
        images: ['https://i.imgur.com/PY8DIXD.jpeg'],
        thumbnail: 'https://i.imgur.com/PY8DIXD.jpeg',
        attributes: {
          bundle_type: 'assistance_kit',
          target_group: ['individual', 'family'],
          dietary_notes: [],
          storage_type: 'dry_and_shelf_stable',
        },
        pricing: {
          currency_mode: 'market_based',
          base_amount: 21.56,
          compare_at_amount: null,
          cost: {
            items_total: 19.86,
            logistics_total: 1.7,
            tax_total: null,
          },
          currency_by_market: [
            {
              market_code: 'LB',
              currency: 'USD',
              amount: 21.56,
            },
          ],
        },
        inventory: {
          track_inventory: false,
          quantity_available: null,
          allow_backorder: true,
          stock_status: 'available',
        },
        availability: {
          is_available: true,
          regions: ['LB'],
          channels: ['donation_platform', 'web'],
          start_date: null,
          end_date: null,
        },
        shipping: {
          requires_shipping: true,
          is_physical: true,
          weight: null,
          dimensions: null,
          shipping_class: 'aid_bundle',
          logistics_item: {
            name: 'Packaging & Delivery',
            amount: 1.7,
          },
        },
        donation: {
          is_donation_product: true,
          donation_type: 'fixed_bundle',
          sponsorship_model: 'one_time',
          impact_unit: 'kit',
          impact_description: 'Provides a basic food assistance bundle.',
          dedication_supported: true,
          recurring_supported: true,
        },
        seo: {
          meta_title: 'Basic Food Assistance Kit',
          meta_description:
            'Donate a basic food assistance kit with essential pantry supplies.',
          slug: 'basic-food-assistance-kit',
        },
        metadata: {
          created_at: null,
          updated_at: null,
          published_at: null,
          external_reference: null,
        },
        components: [
          {
            id: 'food_meat_340g',
            sku: 'FOOD-MEAT-340G',
            type: 'item',
            name: 'Canned Meat',
            description: 'Shelf-stable canned meat.',
            quantity: 3,
            unit_of_measure: 'unit',
            pack_size: '340g',
            unit_price: 1.4,
            total_price: 4.2,
            attributes: {
              category: 'protein',
              brand: 'Taghziya',
            },
          },
          {
            id: 'food_cheese_100g',
            sku: 'FOOD-CHEESE-100G',
            type: 'item',
            name: 'Canned Cheese',
            description: 'Shelf-stable canned cheese.',
            quantity: 3,
            unit_of_measure: 'unit',
            pack_size: '100g',
            unit_price: 0.59,
            total_price: 1.77,
            attributes: {
              category: 'dairy',
              brand: 'Bella',
            },
          },
          {
            id: 'food_hummus_400g',
            sku: 'FOOD-HUMMUS-400G',
            type: 'item',
            name: 'Hummus Tahini',
            description: 'Prepared hummus tahini.',
            quantity: 6,
            unit_of_measure: 'unit',
            pack_size: '400g',
            unit_price: 0.6,
            total_price: 3.6,
            attributes: {
              category: 'spread',
            },
          },
          {
            id: 'food_beans_400g',
            sku: 'FOOD-BEANS-400G',
            type: 'item',
            name: 'Canned Beans',
            description: 'Shelf-stable canned beans.',
            quantity: 2,
            unit_of_measure: 'unit',
            pack_size: '400g',
            unit_price: 0.88,
            total_price: 1.76,
            attributes: {
              category: 'legumes',
            },
          },
          {
            id: 'food_sugar_900g',
            sku: 'FOOD-SUGAR-900G',
            type: 'item',
            name: 'Sugar',
            description: 'Granulated sugar.',
            quantity: 1,
            unit_of_measure: 'unit',
            pack_size: '900g',
            unit_price: 0.73,
            total_price: 0.73,
            attributes: {
              category: 'pantry',
            },
          },
          {
            id: 'food_halawa_400g',
            sku: 'FOOD-HALAWA-400G',
            type: 'item',
            name: 'Halawa',
            description: 'Plain halawa sweet.',
            quantity: 1,
            unit_of_measure: 'unit',
            pack_size: '400g',
            unit_price: 1.27,
            total_price: 1.27,
            attributes: {
              category: 'sweet',
            },
          },
          {
            id: 'food_kaak_300g',
            sku: 'FOOD-KAAK-300G',
            type: 'item',
            name: 'Sesame Kaak',
            description: 'Sesame-coated kaak biscuits.',
            quantity: 3,
            unit_of_measure: 'unit',
            pack_size: '300g',
            unit_price: 1.55,
            total_price: 4.65,
            attributes: {
              category: 'bakery',
            },
          },
          {
            id: 'food_dates_500g',
            sku: 'FOOD-DATES-500G',
            type: 'item',
            name: 'Dates',
            description: 'Packaged dates.',
            quantity: 1,
            unit_of_measure: 'unit',
            pack_size: '500g',
            unit_price: 1.35,
            total_price: 1.35,
            attributes: {
              category: 'fruit',
            },
          },
          {
            id: 'food_tea_25',
            sku: 'FOOD-TEA-25',
            type: 'item',
            name: 'Tea Bags',
            description: 'Tea bags pack.',
            quantity: 1,
            unit_of_measure: 'box',
            pack_size: '25 sachets',
            unit_price: 0.53,
            total_price: 0.53,
            attributes: {
              category: 'beverage',
            },
          },
        ],
      },
      {
        id: 'hygiene_kit_standard',
        sku: 'BUNDLE-HYGIENE-STD-001',
        slug: 'personal-hygiene-kit',
        type: 'bundle',
        status: 'active',
        category: {
          id: 'hygiene',
          name: 'Hygiene',
        },
        tags: ['donation', 'hygiene', 'care', 'bundle', 'essential'],
        title: 'Personal Hygiene Kit',
        subtitle: 'Daily hygiene and personal care essentials',
        description:
          'A donation bundle containing personal hygiene and daily-use items that support cleanliness, comfort, and dignity.',
        short_description: 'Complete personal hygiene support bundle.',
        brand: null,
        vendor: null,
        images: ['https://i.imgur.com/4LkpaNz.png'],
        thumbnail: 'https://i.imgur.com/4LkpaNz.png',
        attributes: {
          bundle_type: 'assistance_kit',
          target_group: ['adult'],
          gender: 'unisex',
        },
        pricing: {
          currency_mode: 'market_based',
          base_amount: 25.87,
          compare_at_amount: null,
          cost: {
            items_total: 24.17,
            logistics_total: 1.7,
            tax_total: null,
          },
          currency_by_market: [
            {
              market_code: 'LB',
              currency: 'USD',
              amount: 25.87,
            },
          ],
        },
        inventory: {
          track_inventory: false,
          quantity_available: null,
          allow_backorder: true,
          stock_status: 'available',
        },
        availability: {
          is_available: true,
          regions: ['LB'],
          channels: ['donation_platform', 'web'],
          start_date: null,
          end_date: null,
        },
        shipping: {
          requires_shipping: true,
          is_physical: true,
          weight: null,
          dimensions: null,
          shipping_class: 'aid_bundle',
          logistics_item: {
            name: 'Packaging & Delivery',
            amount: 1.7,
          },
        },
        donation: {
          is_donation_product: true,
          donation_type: 'fixed_bundle',
          sponsorship_model: 'one_time',
          impact_unit: 'kit',
          impact_description: 'Provides a personal hygiene support bundle.',
          dedication_supported: true,
          recurring_supported: true,
        },
        seo: {
          meta_title: 'Personal Hygiene Kit',
          meta_description:
            'Donate a personal hygiene kit with essential care products.',
          slug: 'personal-hygiene-kit',
        },
        metadata: {
          created_at: null,
          updated_at: null,
          published_at: null,
          external_reference: null,
        },
        components: [
          {
            id: 'hygiene_soap_liquid_500ml',
            sku: 'HYGIENE-SOAP-LIQUID-500ML',
            type: 'item',
            name: 'Liquid Hand Soap',
            description: 'Liquid hand soap for daily cleaning.',
            quantity: 1,
            unit_of_measure: 'unit',
            pack_size: '500ml',
            unit_price: 0.97,
            total_price: 0.97,
            attributes: {
              category: 'soap',
            },
          },
          {
            id: 'hygiene_shampoo_1l',
            sku: 'HYGIENE-SHAMPOO-1L',
            type: 'item',
            name: 'Hair Shampoo',
            description: 'Hair shampoo for routine washing.',
            quantity: 1,
            unit_of_measure: 'unit',
            pack_size: '1L',
            unit_price: 1.25,
            total_price: 1.25,
            attributes: {
              category: 'haircare',
            },
          },
          {
            id: 'hygiene_soap_bar',
            sku: 'HYGIENE-SOAP-BAR',
            type: 'item',
            name: 'Washing Soap Bar',
            description: 'Bar soap for washing.',
            quantity: 1,
            unit_of_measure: 'unit',
            pack_size: null,
            unit_price: 0.97,
            total_price: 0.97,
            attributes: {
              category: 'soap',
            },
          },
          {
            id: 'hygiene_comb',
            sku: 'HYGIENE-COMB',
            type: 'item',
            name: 'Hair Comb',
            description: 'Basic grooming comb.',
            quantity: 1,
            unit_of_measure: 'unit',
            pack_size: null,
            unit_price: 0.43,
            total_price: 0.43,
            attributes: {
              category: 'grooming',
            },
          },
          {
            id: 'hygiene_nail_cutter',
            sku: 'HYGIENE-NAIL-CUTTER',
            type: 'item',
            name: 'Nail Cutter',
            description: 'Nail cutting tool.',
            quantity: 1,
            unit_of_measure: 'unit',
            pack_size: null,
            unit_price: 0.7,
            total_price: 0.7,
            attributes: {
              category: 'grooming',
            },
          },
          {
            id: 'hygiene_loofa',
            sku: 'HYGIENE-LOOFA',
            type: 'item',
            name: 'Body Loofa',
            description: 'Bath sponge for body washing.',
            quantity: 1,
            unit_of_measure: 'unit',
            pack_size: null,
            unit_price: 0.75,
            total_price: 0.75,
            attributes: {
              category: 'bath',
            },
          },
          {
            id: 'hygiene_towel_thin',
            sku: 'HYGIENE-TOWEL-THIN',
            type: 'item',
            name: 'Thin Towel',
            description: 'Lightweight towel.',
            quantity: 2,
            unit_of_measure: 'unit',
            pack_size: null,
            unit_price: 0.6,
            total_price: 1.2,
            attributes: {
              category: 'linen',
            },
          },
          {
            id: 'hygiene_towel_hand',
            sku: 'HYGIENE-TOWEL-HAND',
            type: 'item',
            name: 'Hand Towel',
            description: 'Hand towel for daily use.',
            quantity: 2,
            unit_of_measure: 'unit',
            pack_size: null,
            unit_price: 1.2,
            total_price: 2.4,
            attributes: {
              category: 'linen',
            },
          },
          {
            id: 'hygiene_tissue',
            sku: 'HYGIENE-TISSUE',
            type: 'item',
            name: 'Facial Tissue Paper',
            description: 'Facial tissues for personal care.',
            quantity: 1,
            unit_of_measure: 'pack',
            pack_size: null,
            unit_price: 0.6,
            total_price: 0.6,
            attributes: {
              category: 'paper_goods',
            },
          },
          {
            id: 'hygiene_wipes',
            sku: 'HYGIENE-WIPES',
            type: 'item',
            name: 'Wet Wipes',
            description: 'Moist wipes for quick cleaning.',
            quantity: 1,
            unit_of_measure: 'pack',
            pack_size: null,
            unit_price: 0.45,
            total_price: 0.45,
            attributes: {
              category: 'paper_goods',
            },
          },
          {
            id: 'hygiene_pyjama',
            sku: 'HYGIENE-PYJAMA',
            type: 'item',
            name: 'Pyjama Set',
            description: 'Basic pyjama clothing set.',
            quantity: 1,
            unit_of_measure: 'set',
            pack_size: null,
            unit_price: 6.75,
            total_price: 6.75,
            attributes: {
              category: 'apparel',
            },
          },
          {
            id: 'hygiene_slippers',
            sku: 'HYGIENE-SLIPPERS',
            type: 'item',
            name: 'Slippers',
            description: 'Indoor slippers.',
            quantity: 1,
            unit_of_measure: 'pair',
            pack_size: null,
            unit_price: 2,
            total_price: 2,
            attributes: {
              category: 'footwear',
            },
          },
          {
            id: 'hygiene_razors',
            sku: 'HYGIENE-RAZORS-5PK',
            type: 'item',
            name: 'Disposable Razors',
            description: 'Pack of disposable razors.',
            quantity: 1,
            unit_of_measure: 'pack',
            pack_size: '5-pack',
            unit_price: 1,
            total_price: 1,
            attributes: {
              category: 'grooming',
            },
          },
          {
            id: 'hygiene_shaving_cream',
            sku: 'HYGIENE-SHAVING-CREAM',
            type: 'item',
            name: 'Shaving Cream',
            description: 'Cream for shaving use.',
            quantity: 1,
            unit_of_measure: 'unit',
            pack_size: null,
            unit_price: 1.25,
            total_price: 1.25,
            attributes: {
              category: 'grooming',
            },
          },
          {
            id: 'hygiene_shaving_brush',
            sku: 'HYGIENE-SHAVING-BRUSH',
            type: 'item',
            name: 'Shaving Brush',
            description: 'Brush used for shaving.',
            quantity: 1,
            unit_of_measure: 'unit',
            pack_size: null,
            unit_price: 0.95,
            total_price: 0.95,
            attributes: {
              category: 'grooming',
            },
          },
          {
            id: 'hygiene_perfume',
            sku: 'HYGIENE-PERFUME',
            type: 'item',
            name: 'Perfume Spray',
            description: 'Personal fragrance spray.',
            quantity: 1,
            unit_of_measure: 'unit',
            pack_size: null,
            unit_price: 1.1,
            total_price: 1.1,
            attributes: {
              category: 'fragrance',
            },
          },
          {
            id: 'hygiene_bag',
            sku: 'HYGIENE-BAG',
            type: 'item',
            name: 'String Bag',
            description: 'Carry bag for hygiene items.',
            quantity: 1,
            unit_of_measure: 'unit',
            pack_size: null,
            unit_price: 1.4,
            total_price: 1.4,
            attributes: {
              category: 'accessory',
            },
          },
        ],
      },
      {
        id: 'baby_care_kit',
        sku: 'BUNDLE-BABY-CARE-001',
        slug: 'baby-care-kit',
        type: 'bundle',
        status: 'active',
        category: {
          id: 'baby',
          name: 'Baby',
        },
        tags: ['donation', 'baby', 'care', 'bundle', 'essential'],
        title: 'Baby Care Kit',
        subtitle: 'Daily baby hygiene and comfort essentials',
        description:
          'A donation bundle containing practical baby care products that support hygiene, comfort, and everyday infant care.',
        short_description: 'Essential baby care support bundle.',
        brand: null,
        vendor: null,
        images: ['https://i.imgur.com/SJgkrWD.jpeg'],
        thumbnail: 'https://i.imgur.com/SJgkrWD.jpeg',
        attributes: {
          bundle_type: 'assistance_kit',
          target_group: ['baby', 'caregiver'],
          age_range: null,
        },
        pricing: {
          currency_mode: 'market_based',
          base_amount: 23.5,
          compare_at_amount: null,
          cost: {
            items_total: 21.8,
            logistics_total: 1.7,
            tax_total: null,
          },
          currency_by_market: [
            {
              market_code: 'LB',
              currency: 'USD',
              amount: 23.5,
            },
          ],
        },
        inventory: {
          track_inventory: false,
          quantity_available: null,
          allow_backorder: true,
          stock_status: 'available',
        },
        availability: {
          is_available: true,
          regions: ['LB'],
          channels: ['donation_platform', 'web'],
          start_date: null,
          end_date: null,
        },
        shipping: {
          requires_shipping: true,
          is_physical: true,
          weight: null,
          dimensions: null,
          shipping_class: 'aid_bundle',
          logistics_item: {
            name: 'Packaging & Delivery',
            amount: 1.7,
          },
        },
        donation: {
          is_donation_product: true,
          donation_type: 'fixed_bundle',
          sponsorship_model: 'one_time',
          impact_unit: 'kit',
          impact_description: 'Provides a baby care support bundle.',
          dedication_supported: true,
          recurring_supported: true,
        },
        seo: {
          meta_title: 'Baby Care Kit',
          meta_description: 'Donate a baby care kit with essential infant products.',
          slug: 'baby-care-kit',
        },
        metadata: {
          created_at: null,
          updated_at: null,
          published_at: null,
          external_reference: null,
        },
        components: [
          {
            id: 'baby_diapers',
            sku: 'BABY-DIAPERS',
            type: 'item',
            name: 'Baby Diapers',
            description: 'Baby diapers for daily use.',
            quantity: 2,
            unit_of_measure: 'pack',
            pack_size: null,
            unit_price: 4.5,
            total_price: 9,
            attributes: {
              category: 'diapering',
            },
          },
          {
            id: 'baby_cream',
            sku: 'BABY-CREAM',
            type: 'item',
            name: 'Baby Cream',
            description: 'Baby skin care cream.',
            quantity: 1,
            unit_of_measure: 'unit',
            pack_size: null,
            unit_price: 2.5,
            total_price: 2.5,
            attributes: {
              category: 'skincare',
            },
          },
          {
            id: 'baby_comb',
            sku: 'BABY-COMB',
            type: 'item',
            name: 'Baby Comb',
            description: 'Comb designed for baby grooming.',
            quantity: 1,
            unit_of_measure: 'unit',
            pack_size: null,
            unit_price: 1,
            total_price: 1,
            attributes: {
              category: 'grooming',
            },
          },
          {
            id: 'baby_shampoo',
            sku: 'BABY-SHAMPOO',
            type: 'item',
            name: 'Baby Shampoo',
            description: 'Gentle shampoo for babies.',
            quantity: 2,
            unit_of_measure: 'unit',
            pack_size: null,
            unit_price: 3,
            total_price: 6,
            attributes: {
              category: 'bath',
            },
          },
          {
            id: 'baby_nail_cutter',
            sku: 'BABY-NAIL-CUTTER',
            type: 'item',
            name: 'Baby Nail Cutter',
            description: 'Nail cutter suitable for baby care.',
            quantity: 1,
            unit_of_measure: 'unit',
            pack_size: null,
            unit_price: 1.5,
            total_price: 1.5,
            attributes: {
              category: 'grooming',
            },
          },
          {
            id: 'baby_perfume',
            sku: 'BABY-PERFUME',
            type: 'item',
            name: 'Baby Perfume',
            description: 'Light fragrance product for babies.',
            quantity: 1,
            unit_of_measure: 'unit',
            pack_size: null,
            unit_price: 1.8,
            total_price: 1.8,
            attributes: {
              category: 'fragrance',
            },
          },
        ],
      },
    ],
  },
};

export default catalogData;